### ISSUE TITLE
Calling specql/update! with an empty WHERE map gives syntax error

### ISSUE THREAD

**Issue by Jarzka** [tatut/specql#16]
The following call 

```
(specql/update! db
                  ::h/hinnoittelu
                  {::m/poistettu? true
                   ::m/poistaja-id (:id user)}
                  {})
```

gave me the following exception:

`ERROR in (poista-hintaryhma) (BatchResultHandler.java:148)
Uncaught exception, not in assertion.
expected: nil
  actual: java.sql.BatchUpdateException: Batch entry 0 UPDATE "vv_hinnoittelu" AS vv_1 SET "poistettu"='1',"poistaja"=2 WHERE  was aborted: ERROR: syntax error at end of input
  Position: 72  Call getNextException to see other errors in the batch.
 at org.postgresql.jdbc.BatchResultHandler.handleError (BatchResultHandler.java:148)
    org.postgresql.core.v3.QueryExecutorImpl.processResults (QueryExecutorImpl.java:2156)
    org.postgresql.core.v3.QueryExecutorImpl.execute (QueryExecutorImpl.java:460)
    org.postgresql.jdbc.PgStatement.executeBatch (PgStatement.java:793)
    org.postgresql.jdbc.PgPreparedStatement.executeBatch (PgPreparedStatement.java:1659)
    com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch (NewProxyPreparedStatement.java:2544)
    clojure.java.jdbc$execute_batch.invokeStatic (jdbc.clj:439)
    clojure.java.jdbc$execute_batch.invoke (jdbc.clj:432)
    clojure.java.jdbc$db_do_execute_prepared_statement$fn__329.invoke (jdbc.clj:820)
    clojure.java.jdbc$db_transaction_STAR_.invokeStatic (jdbc.clj:662)
    clojure.java.jdbc$db_transaction_STAR_.invoke (jdbc.clj:598)
    clojure.java.jdbc$db_transaction_STAR_.invokeStatic (jdbc.clj:611)
    clojure.java.jdbc$db_transaction_STAR_.invoke (jdbc.clj:598)
    clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic (jdbc.clj:819)
    clojure.java.jdbc$db_do_execute_prepared_statement.invoke (jdbc.clj:806)
    clojure.java.jdbc$db_do_prepared.invokeStatic (jdbc.clj:843)
    clojure.java.jdbc$db_do_prepared.invoke (jdbc.clj:823)
    clojure.java.jdbc$execute_BANG_$execute_helper__366.invoke (jdbc.clj:1008)
    clojure.java.jdbc$execute_BANG_.invokeStatic (jdbc.clj:1010)
    clojure.java.jdbc$execute_BANG_.invoke (jdbc.clj:989)
    clojure.java.jdbc$execute_BANG_.invokeStatic (jdbc.clj:1000)
    clojure.java.jdbc$execute_BANG_.invoke (jdbc.clj:989)
    specql.impl.update$update_BANG_.invokeStatic (update.clj:35)
    specql.impl.update$update_BANG_.invoke (update.clj:9)
    specql.core$update_BANG_.invokeStatic (core.clj:74)
    specql.core$update_BANG_.invoke (core.clj:71)`

Obviously the empty WHERE map was a mistake, but I think it should still work?

**Comment by tatut** [comment]
This should be asserted with a nice error message, the same as with delete!

**Comment by Jarzka** [comment]
Is this issue fixed now? I tried using an empty WHERE map and got the result as expected.
