### ISSUE TITLE
Change Request: Support for JSON-datatype columns

### ISSUE THREAD

**Issue by mikkoronkkomaki** [tatut/specql#17]
It would be more than convenient, if you would be able to serialize and deserialize JSON type columns automatically e.g. using Cheshire, when writing and reading tables with such columns. In addition, would it be possible to defined nested specs, which would validate the datastructures within the JSON payloads?

**Comment by tatut** [comment]
Use a transform on the column. 

I don't want to add a cheshire (or other JSON library) dependency. Creating a transform that does encode/decode as required is the preferred way to integrate.

Specql transform protocol (see https://github.com/tatut/specql/blob/master/src/specql/transform.cljc#L6) already supports  transforming the actual column spec so you can have a spec for the nested JSON.
