### ISSUE TITLE
Table and column renaming

### ISSUE THREAD

**Issue by jaaqo** [tatut/specql#24]
As like many others, I have all SQL tables and columns using underscores. In Clojure it is more idiomatic to use dashes.

Would it be possible to add a feature that would do this conversion under the hood if chosen so?

**Comment by jaaqo** [comment]
This is an example I guess this issue is currently supposed to be handled:
```clojure
(specql/define-tables *db*
  ["shop_type" :shop-type/shop-types]
  ["shop" :shop/shops
   {"shop_type_id" :shop/shop-type-id} ;; Renaming
   {:shop/shop-type (rel/has-one :shop/shop-type-id
                                 :shop-type/shop-types
                                 :shop-type/id)}])
```

**Comment by tatut** [comment]
That's a good idea, though I would probably add a simple `:transform-column-name` function as a parameter that can do arbitrary transformation (given name, returns transformed name).

Definitely a good candidate for next release, thanks.

**Comment by tatut** [comment]
Column names can be transformed in the next version:

```clojure
(define-tables 
  {:specql.core/db db-connection
   :specql.core/transform-column-name (fn [ns column-name] ...code...)
 ...)
```

**Comment by tatut** [comment]
The transform-column-name option can do arbitrary transformations as long as it returns a qualified key. There's a test for it in the test suite.
