### ISSUE TITLE
`op/and` fails if all parameters are nil

### ISSUE THREAD

**Issue by Kauko** [tatut/specql#29]
```
(op/and
  (when something ...)
  (when something-else ...))
```

I'd say this is probably pretty common, but right now it seems `op/and` can't handle it. The result looks to be `["(AND)"]`

```
[op & ops] (remove nil? ops)]
      (if-not op
        [(str "(" (str/join combine-with sql) ")") params]
```

**Comment by tatut** [comment]
What version are you using? I'm getting "()" as the generated SQL.
